main:
  steps:
  - init:
      assign:
      - project_id: "profitscout-lx6bb"
      - region: "us-central1"
      - price_updater_name: "refresh-prices"
      - news_fetcher_name: "fetch-news"
      - fundamentals_name: "refresh-fundamentals"
      - technicals_name: "refresh-technicals"
      - sec_extractor_name: "extract-sec-filings"
      - refresh_financials_name: "refresh-financials"
      - price_data_populator_name: "populate-price-data"
      - refresh_stock_metadata_name: "refresh-stock-metadata"
      - calendar_events_name: "refresh-calendar-events"

  - call_price_updater:
      call: http.post
      args:
          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + price_updater_name}
          auth: {type: OIDC}
          timeout: 900
  - call_fundamentals:
      call: http.post
      args:
          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + fundamentals_name}
          auth: {type: OIDC}
          timeout: 900
  - call_technicals:
      call: http.post
      args:
          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + technicals_name}
          auth: {type: OIDC}
          timeout: 900
  - call_sec_extractor:
      call: http.post
      args:
          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + sec_extractor_name}
          auth: {type: OIDC}
          timeout: 900
  - call_refresh_financials:
      call: http.post
      args:
          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + refresh_financials_name}
          auth: {type: OIDC}
          timeout: 900
  - call_price_data_populator:
      call: http.post
      args:
          url: ${"https://us-central1-profitscout-lx6bb.cloudfunctions.net/populate-price-data"}
          auth: {type: OIDC}
          timeout: 900
  - call_refresh_stock_metadata:
      call: http.post
      args:
          url: ${"https://us-central1-profitscout-lx6bb.cloudfunctions.net/refresh-stock-metadata"}
          auth: {type: OIDC}
          timeout: 900
  - call_calendar_events:
      call: http.post
      args:
          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + calendar_events_name}
          auth: {type: OIDC}
          timeout: 900
  - call_news_fetcher:
      call: http.post
      args:
          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + news_fetcher_name}
          auth: {type: OIDC}
          timeout: 900

  - log_finish:
      call: sys.log
      args:
        text: "Main data collection workflow finished successfully."
  - done:
      return: "Workflow finished successfully."