# serving/workflow.yaml
main:
  steps:
    - init:
        assign:
          - project_id: "profitscout-lx6bb"
          - region: "us-central1"
          - score_aggregator_name: "score-aggregator"
          - recommendation_generator_name: "recommendation-generator"
          - data_bundler_name: "data-bundler"
          - sync_to_firestore_name: "sync-to-firestore"

    - call_score_aggregator:
        call: http.post
        args:
          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + score_aggregator_name}
          auth: { type: OIDC }
          timeout: 900
        result: score_aggregator_result

    - call_recommendation_generator:
        call: http.post
        args:
          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + recommendation_generator_name}
          auth: { type: OIDC }
          timeout: 900
        result: recommendation_generator_result

    - call_data_bundler:
        call: http.post
        args:
          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + data_bundler_name}
          auth: { type: OIDC }
          timeout: 900
        result: data_bundler_result
    
    - call_sync_to_firestore:
        call: http.post
        args:
          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + sync_to_firestore_name}
          auth: { type: OIDC }
          timeout: 900
        result: sync_to_firestore_result

    - log_finish:
        call: sys.log
        args:
          text: "Serving workflow (scoring, recommendation, bundling, and sync) finished successfully."

    - done:
        return: "Serving workflow finished successfully."